###create a new product
POST http://localhost:3000/products 
Content-Type: application/json

{
    "name": "dddadad",
    "description": "fdfdffdf",
    "price": 40,
    "quantityInStock": 1
}



###get all products
GET http://localhost:3000/products


###update  a product by id
PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Updated Product Name",
    "description": "Updated product description.",
    "price": 50,
    "quantityInStock": 10
}


### Delete a product by ID
DELETE http://localhost:3000/products/1

### Create a new user
POST http://localhost:3000/authentication/register

Content-Type: application/json


{
    "username": "lester",
    "email": "lester@example.com",
    "password": "newuserpassword",
    "role": "manager"
}

### login admin
POST http://localhost:3000/authentication/login
Content-Type: application/json


{
    
    "email": "newuser@example.com",
    "password": "newuserpassword"
}




### Admin creating a new user
POST http://localhost:3000/authentication/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczODMyNTc2NSwiZXhwIjoxNzM4MzI5MzY1fQ.0o21DEtGeGtagu2abMvWIrqWIDA3Yvru-0IFK3Khs8E

{
    "username": "newuser2",
    "email": "newuser2@example.com",
    "password": "newuserpassword2",
    "role": "user"
}











### Get all users
GET http://localhost:3000/users

### Get a user by ID
GET http://localhost:3000/users/1

### Update a user by ID
PUT http://localhost:3000/users/1
Content-Type: application/json
Role: admin

{
    "username": "updateduser",
    "email": "updateduser@example.com",
    "password": "updateduserpassword",
    "role": "admin"
}

### Delete a user by ID
DELETE http://localhost:3000/users/1
Role: admin

### Register a new user
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com",
    "password": "newuserpassword",
    "role": "user"
}

### Login a user
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "newuserpassword"
}

### Verify a token
GET http://localhost:3000/verify
Authorization: Bearer YOUR_JWT_TOKEN_HERE

### Create a new inventory record
POST https://inventory-backend-u8wv.onrender.com/inventory
Content-Type: application/json

{
    "productid": 2,
    "quantityAvailable": 100,
    "reorderLevel": 20
}

### Get all inventory records
GET http://localhost:3000/inventory

### Get an inventory record by ID
GET http://localhost:3000/inventory/1

### Update an inventory record by ID
PUT http://localhost:3000/inventory/1
Content-Type: application/json

{
    "productid": 1,
    "quantityAvailable": 150,
    "reorderLevel": 30
}

### Delete an inventory record by ID
DELETE http://localhost:3000/inventory/1

### Create a new order
POST http://localhost:3000/orders
Content-Type: application/json

{
    "userid": 1,
    "productid": 2,
    "quantityOrdered": 10,
    "orderDate": "2023-10-01T00:00:00.000Z"
}

### Get all orders
GET http://localhost:3000/orders

### Get an order by ID
GET http://localhost:3000/orders/1

### Update an order by ID
PUT http://localhost:3000/orders/1
Content-Type: application/json

{
    "userid": 1,
    "productid": 1,
    "quantityOrdered": 15,
    "orderDate": "2023-10-01T00:00:00.000Z"
}

### Delete an order by ID
DELETE http://localhost:3000/orders/1

### Create a new sale
POST http://localhost:3000/sales
Content-Type: application/json

{
    "orderid": 2,
    "saleDate": "2023-10-01T00:00:00.000Z",
    "totalAmount": 100.00
}

### Get all sales
GET http://localhost:3000/sales

### Get a sale by ID
GET http://localhost:3000/sales/1

### Update a sale by ID
PUT http://localhost:3000/sales/1
Content-Type: application/json

{
    "orderid": 1,
    "saleDate": "2023-10-01T00:00:00.000Z",
    "totalAmount": 150.00
}

### Delete a sale by ID
DELETE http://localhost:3000/sales/1

### Create a new supplier
POST http://localhost:3000/suppliers
Content-Type: application/json

{
    "name": "New Supplier",
    "contactInfo": "Contact Info"
}

### Get all suppliers
GET http://localhost:3000/suppliers

### Get a supplier by ID
GET http://localhost:3000/suppliers/1

### Update a supplier by ID
PUT http://localhost:3000/suppliers/1
Content-Type: application/json

{
    "name": "Updated Supplier",
    "contactInfo": "Updated Contact Info"
}

### Delete a supplier by ID
DELETE http://localhost:3000/suppliers/1

### Create a new prediction
POST http://localhost:3000/predictions
Content-Type: application/json

{
    "productid": 2,
    "predictedDemand": 100,
    "predictionDate": "2023-10-01T00:00:00.000Z"
}

### Get all predictions
GET http://localhost:3000/predictions

### Get a prediction by ID
GET http://localhost:3000/predictions/1

### Update a prediction by ID
PUT http://localhost:3000/predictions/1
Content-Type: application/json
{
    "productid": 1,
    "predictedDemand": 150,
    "predictionDate": "2023-10-01T00:00:00.000Z"
}

### Delete a prediction by ID
DELETE http://localhost:3000/predictions/1






https://inventory-backend-u8wv.onrender.com