###create a new product
POST http://localhost:3000/products 
Content-Type: application/json

{
    "name": "dddadad",
    "description": "fdfdffdf",
    "price": 40,
    "quantityInStock": 1
}



###get all products
GET http://localhost:3000/products


###update  a product by id
PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Updated Product Name",
    "description": "Updated product description.",
    "price": 50,
    "quantityInStock": 10
}


### Delete a product by ID
DELETE http://localhost:3000/products/1